- name: Make .zsh directory
  file:
    state: directory
    path: ~/.zsh

- name: Make completions directory
  file:
    state: directory
    path: ~/.zsh/completions

- name: Copy .zshenv
  copy:
    src: ../files/.zshenv
    dest: /home/vagrant/.zshenv

- name: Copy .zprofile
  copy:
    src: ../files/.zprofile
    dest: /home/vagrant/.zprofile

- name: Copy .zshrc
  copy:
    src: ../files/.zshrc
    dest: /home/vagrant/.zshrc

- name: Copy .zlogin
  copy:
    src: ../files/.zlogin
    dest: /home/vagrant/.zlogin

- name: Copy .zlogout
  copy:
    src: ../files/.zlogout
    dest: /home/vagrant/.zlogout

- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: Set zsh as default shell
  become: yes
  user:
    name: vagrant
    shell: /usr/bin/zsh
