- name: Make .vim directory
  file:
    state: directory
    path: ~/.vim

- name: Copy .vimrc
  copy:
    src: ../files/.vimrc
    dest: ~/.vimrc

- name: Copy .vim/encode_ja.vim
  copy:
    src: ../files/.vim/encode_ja.vim
    dest: ~/.vim/encode_ja.vim
